version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --cache-from=solidity -t newridetech/solidity .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker tag newridetech/solidity newridetech/solidity:latest
      - run: docker push newridetech/solidity:latest
